name: hypnettorch
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - async-timeout=4.0.2
  - asynctest=0.13.0
  - attrs=22.1.0
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cachetools=4.2.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - cryptography=39.0.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - expat=2.4.9
  - fftw=3.3.9
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - giflib=5.2.1
  - glib=2.69.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - grpcio=1.42.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=7.31.1
  - jedi=0.18.1
  - joblib=1.1.1
  - jpeg=9e
  - jupyter_client=7.4.9
  - jupyter_core=4.11.2
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.9
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy-base=1.21.5
  - oauthlib=3.2.1
  - openssl=1.1.1w
  - packaging=22.0
  - pandas=1.3.5
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - ply=3.11
  - prompt-toolkit=3.0.36
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.7.16
  - python-dateutil=2.8.2
  - pytz=2022.7
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.12.2
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorboardx=2.2
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - wcwidth=0.2.5
  - werkzeug=2.2.2
  - wheel=0.38.4
  - xz=5.4.2
  - yarl=1.8.1
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - appdirs==1.4.4
    - backports-zoneinfo==0.2.1
    - chardet==5.2.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - docker-pycreds==0.4.0
    - future==0.18.3
    - gitdb==4.0.11
    - gitpython==3.1.40
    - hypnettorch==0.0.4
    - imageio==2.31.2
    - importlib-metadata==6.7.0
    - ipdb==0.13.13
    - networkx==2.6.3
    - numpy==1.21.6
    - pathtools==0.1.2
    - pillow==9.5.0
    - py==1.11.0
    - pywavelets==1.3.0
    - pyyaml==6.0.1
    - requests==2.31.0
    - retry==0.9.2
    - scikit-image==0.19.3
    - sentry-sdk==1.34.0
    - setproctitle==1.3.3
    - smmap==5.0.1
    - tifffile==2021.11.2
    - tomli==2.0.1
    - torch==1.10.1
    - torchvision==0.11.2
    - tzlocal==5.1
    - urllib3==2.0.7
    - wandb==0.15.12
    - zipp==3.15.0
